### ISSUE TITLE
KonashiBaseManager.java l.627のcharacteristic.getDescriptorがnullを返す

### ISSUE THREAD

**Issue by e10dokup** [YUKAI/konashi-android-sdk#1]

**Comment by e10dokup** [comment]
返って来たdescriptorがnullの場合に何もしない…ってことでいいのか？

**Comment by izumin5210** [comment]
characteristicがdescriptorを持っていない場合，descriptorを手動でinstantiateしたうえでcharacteristicにaddすればよい．
ただし，3つのcharacteristicに対して連続で書き込もうとしているため，現状だとちゃんと処理できない（最初の`writeDescriptor()`のみ生き残る）．

**Comment by izumin5210** [comment]
Bletia側でなんとかした
