### ISSUE TITLE
typo onDisconncted => onDisconnected

### ISSUE THREAD

**Issue by kiryuxxu** [YUKAI/konashi-android-sdk#10]
KonashiObserver のメソッド名が間違っています。

`public void onDisconncted(){}`

https://github.com/e10dokup/konashi-v2-android-sdk/blob/54e4e6371139d10cb9798c0394f3d7c5f425364d/Konashi/konashi-v2-android-sdk/src/main/java/com/uxxu/konashi/lib/KonashiObserver.java#L59

**Comment by izumin5210** [comment]
close via #20

**Comment by izumin5210** [comment]
close via #20
