### ISSUE TITLE
Konashi の電源を落とした場合 KonashiListener#onError() は呼ばれるが KonashiListener#onDisconnect() が呼ばれない。

### ISSUE THREAD

**Issue by kiryuxxu** [YUKAI/konashi-android-sdk#110]
BluetoothGattCallback#onConnectionStateChange() の仕様を見ると

> public void onConnectionStateChange (BluetoothGatt gatt, int status, int newState)
> 
> Added in API level 18
> Callback indicating when GATT client has connected/disconnected to/from a remote GATT server.
> 
> Parameters
> gatt    GATT client
> status  Status of the connect or disconnect operation. GATT_SUCCESS if the operation succeeds.
> newState    Returns the new connection state. Can be one of STATE_DISCONNECTED or STATE_CONNECTED
> https://developer.android.com/intl/ja/reference/android/bluetooth/BluetoothGattCallback.html#onConnectionStateChange(android.bluetooth.BluetoothGatt, int, int)

なので Bletia の実装を `status != GATT_SUCCES && newState == STATE_DISCONNECTED` の場合も `onDisconnect()` とするべきではないでしょうか?

BluetoothGattCallbackHandler.class

``` java
    public void onConnectionStateChange(BluetoothGattWrapper gatt, int status, int newState) {
        if(status == 0) {
            if(newState == 2) {
                this.mCallback.onConnect(gatt);
            }

            if(newState == 0) {
                this.mCallback.onDisconnect(gatt);
            }
        } else {
            this.mCallback.onError(new BletiaException(BleErrorType.valueOf(status)));
        }
    }
```

**Comment by izumin5210** [comment]
ありがとうございます
Bletia側で対応しておきます
