### ISSUE TITLE
KonashiErrorTypeをもう少し詳しくする

### ISSUE THREAD

**Issue by izumin5210** [YUKAI/konashi-android-sdk#111]
#107

**Comment by izumin5210** [comment]
- PIO
  - INVALID_PIN_NUMBER
  - INVALID_MODE
  - INVALID_PULLUP_PARAM
  - INVALID_OUTPUT_PARAM
- AIO
  - INVALID_PIN_NUMBER
- PWM
  - INVALID_PIN_NUMBER
  - INVALID_MODE
- UART
  - DATA_SIZE_TOO_LONG
  - INVALID_MODE
  - INVALID_BAUDRATE
- I2C
  - DATA_SIZE_TOO_LONG
  - INVALID_MODE

**Comment by izumin5210** [comment]
各ErrorTypeにPrefixは不要（`PIO_`みたいなやつ）．
`DATA_SIZE_TOO_LONG`とか`INVALID_MODE`は共通で良さそう．

あと，PWMのDutyとPeriodの扱いが微妙…．

**Comment by e10dokup** [comment]
- [ ] AioAnalogReadAction
- [ ] AioAnalogReadAction

**Comment by izumin5210** [comment]
TOO_SHORT 必要そう
