### ISSUE TITLE
サンプルアプリをよりシンプルにする

### ISSUE THREAD

**Issue by sagiii** [YUKAI/konashi-android-sdk#113]
#46 と関連しますが、

iOSSDKのサンプルや、Arduinoのサンプルのように、本当に最小限のコードだけが含まれていて、「こんなに簡単に動かせるんだ！」と思えるようなものが嬉しいです。

ご参考までに、Arduinoの例を貼ります：
PIO
https://www.arduino.cc/en/Reference/DigitalWrite
AIO
https://www.arduino.cc/en/Reference/AnalogRead
PWM
https://www.arduino.cc/en/Reference/AnalogWrite
UART
https://www.arduino.cc/en/Serial/Write
i2c
https://www.arduino.cc/en/Reference/WireWrite
ご検討のほど、お願いいたします。

**Comment by e10dokup** [comment]
#114 #121 #122  #125 #127 にて対応しました
