### ISSUE TITLE
"Getting Started"ページのコードについて

### ISSUE THREAD

**Issue by tec9w0rks** [YUKAI/konashi-android-sdk#169]
すみません。大したことない話ですが、
http://konashi.ux-xu.com/android/#getting-started
の「5. MainActivityのコードを書く」の部分でのonCreateメソッドの中に、
以下も追加しないとコンパイルエラーが取れませんでした。

@Override
public void onUpdateSpiMiso(KonashiManager manager, byte[] value) {}

**Comment by TsujiTakt** [comment]
ご指摘ありがとうございます。

SDKのSPI対応時にGettingStartedの更新を失念しておりました。
対応致しました。
