### ISSUE TITLE
Android 6 で disconnect すると konashi への入力処理を取得できない

### ISSUE THREAD

**Issue by kiryuxxu** [YUKAI/konashi-android-sdk#192]
## 再現環境

Android: Nexus 5x (Android 6.0.1)
KonashiInspector: https://github.com/YUKAI/KonashiInspectorForAndroid/tree/1.1
Firmware: 2.1.4
konashi SDK: 2.0.0
PC 側アプリ: CoolTerm
## 再現方法
1. konashi と PC を FTDI USB シリアル変換アダプタで接続。
2. Android から KonashiInspector で konashi に接続。
3. アプリの UART パネルを開き、baudrate 9600 で PC 側からの入力を受け取れる事を確認。
4. アプリと konashi の接続を切る。
5. アプリと konashi を再接続して UART のトグルスイッチを OFF => ON にする。
6. 再度 PC からの入力を受け取れるか確認。
## 補足
- アプリを閉じて再度開くと正常に UART が受け取れる。
- UART 以外にも PIO 入力等が受け取れていない。
- https://github.com/YUKAI/konashi-android-sdk/blob/master/konashi-android-sdk/src/main/java/com/uxxu/konashi/lib/CallbackHandler.java#L75 が呼ばれていないような気がする。
- iOS 版 konashi inspector では正常に動作する。

**Comment by tfuru** [comment]
htc HTV31 (Android 5.0)  FTJ152A-Priori3 LTE(Android 5.1) でも同じ不具合を確認しました。

> UART 以外にも PIO 入力等が受け取れていない。
> PIO 0のボタンも反応しなくなる事が確認できました。
