### ISSUE TITLE
konashi（無印）に対応させる

### ISSUE THREAD

**Issue by e10dokup** [YUKAI/konashi-android-sdk#3]
- 取り敢えずUUIDを2クラスに分離させる？
- findしたkonashiのネームで取得するクラス変えたらいんじゃね感
- konashi（初代）のBASE_UUIDください

**Comment by e10dokup** [comment]
どうやらkonashi1だけBluetooth SIG標準らしいのでBASE_UUIDは ”00000000-0000-1000-8000-00805f9b34fb”らしい

**Comment by e10dokup** [comment]
よくよく考えたらHashMap使えばちょっといいかんじに実装できそう

**Comment by izumin5210** [comment]
定数に`HashMap`はどうなんだろう…
`enum`つかうのが無難な気が

**Comment by izumin5210** [comment]
たとえば`KonashiUUID`を`enum`にしておいて，下記のようなUtilityメソッドを定義するとか．

``` java
KonashiUtils.getUUID2(KonashiUUID.BATTERY_SERVICE)
// => 229B180F-03FB-40DA-98A7-B0DEF65C2D4B

KonashiUtils.getUUID1(KonashiUUID.BATTERY_SERVICE)
// => ????????-03FB-40DA-98A7-B0DEF65C2D4B
```

**Comment by e10dokup** [comment]
@izumin5210 なるほど強い

**Comment by izumin5210** [comment]
- [ ] initialize
- [ ] find
- [ ] disconnect
- [ ] isConnected
- [ ] peripheralName
- [ ] pinMode
- [ ] pinPullup
- [ ] digitalRead
- [ ] digitalWrite
- [ ] analogReadRequest
- [ ] analogRead
- [ ] pwmMode
- [ ] pwmPeriod
- [ ] pwmDuty
- [ ] uartMode
- [ ] uartBaudrate
- [ ] uartWrite
- [ ] i2cMode
- [ ] i2cStartCondition
- [ ] i2cStopCondition
- [ ] i2cWrite
- [ ] i2cReadRequest
- [ ] i2cRead
- [ ] reset
- [ ] batteryLevelReadRequest
- [ ] batteryLevelRead
- [ ] signalStrengthReadRequest
- [ ] singalStrengthRead

**Comment by izumin5210** [comment]
一旦close（また気が向いたらやる）
