### ISSUE TITLE
KonashiObserver holds a reference to activity

### ISSUE THREAD

**Issue by e10dokup** [YUKAI/konashi-android-sdk#5]
https://github.com/e10dokup/konashi-v2-android-sdk/blob/develop/Konashi/konashi-v2-android-sdk/src/main/java/com/uxxu/konashi/lib/KonashiNotifier.java#L87

無限につらいので

https://github.com/greenrobot/EventBus/blob/annotations/EventBus/src/de/greenrobot/event/Subscribe.java#L16

みたいに受け側でスレッド選択できるとかの対策が必要っぽい

**Comment by izumin5210** [comment]
`KonashiListener`の導入により解決
