### ISSUE TITLE
android-maven-pluginのclasspathがのversionがふるい

### ISSUE THREAD

**Issue by e10dokup** [YUKAI/konashi-android-sdk#56]
## What

https://github.com/YUKAI/konashi-android-sdk/blob/master/build.gradle#L10

の通り，classpathの指定を

```
classpath 'com.github.dcendents:android-maven-plugin:1.2'
```

にしていると，gradle syncを実行した際に

```
Error:Error:line (44)Cause: org/gradle/api/publication/maven/internal/DefaultMavenFactory
```

でgradleが失敗する（久々にsyncしたやつor新規にsyncしたやつが発症）
## How

とりあえずclasspathの指定を

https://plugins.gradle.org/plugin/com.github.dcendents.android-maven

にそって

```
classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'
```

に変更するとgradle syncが通る

**Comment by izumin5210** [comment]
close via #57
