### ISSUE TITLE
AIO1, AIO2 の read で返ってくる値がおかしい

### ISSUE THREAD

**Issue by kiryuxxu** [YUKAI/konashi-android-sdk#7]
320度のポテンショメーターを通した電圧を AIO0, AIO1, AIO2 で計測してみたのですが、AIO1, AIO2 の値がおかしいです。
以下の表は約45度ずつポテンショメーターを回していった際の AIO の値で、AIO0 の値が正常な値です。

| AIO0 | AIO1 | AIO2 |
| --- | --- | --- |
| 0.002 | 0.003 | 0.002 |
| 0.216 | 0.220 | 0.216 |
| 0.432 | 0.227 | 0.215 |
| 0.432 | 0.227 | 0.215 |
| 0.911 | 0.181 | 0.178 |
| 1.168 | 0.145 | 0.209 |
| 1.331 | 0.053 | 0.129 |

**Comment by sagiii** [comment]
連続回転している様子で見ると、0バイト目と1バイト目が入れ替わっているときの挙動に見えました。

**Comment by e10dokup** [comment]
@sagiii @kiryuxxu @izumin5210 

pull request #15 にAIO1，AIO2の値を修正したpull requestを飛ばしました．
念の為に，テストアプリでAIO1，AIO2の値を確認できるように変更しました．
https://dply.me/exxzx5
