### ISSUE TITLE
pwmPeriod, pwmDuty の間に Thread.sleep を入れないと安定しない

### ISSUE THREAD

**Issue by kiryuxxu** [YUKAI/konashi-android-sdk#8]
``` java
mKonashiManager.pwmPeriod(mPinNumber, period);
mKonashiManager.pwmDuty(mPinNumber, duty);
```

上記のように `pwmPeriod` と `pmwDuty` を連続して実行する場合、`Thread.sleep` を間に入れないと動作が安定しません。

``` java
mKonashiManager.pwmPeriod(mPinNumber, period);
Thread.sleep(100);
mKonashiManager.pwmDuty(mPinNumber, duty);
```

**Comment by sagiii** [comment]
@kiryuxxu と話して、sdkにsleepを（100は長い気もしますが）入れるでもいいかなと思っています。（ios-sdkもi2c周りですが１箇所入ってます）

**Comment by izumin5210** [comment]
Androidアプリケーションにおいて，UI Threadをブロックするのはバッドプラクティスになります（実際，ある程度以上ブロックされたらExceptionが投げられる）．
イベントが発行されるスレッドを選択できない以上はドキュメント上で注意喚起するのがいいと思われますが，如何でしょうか．

**Comment by izumin5210** [comment]
SDKがユーザに無断で`Thread.sleep()`するより，`KonashiObserver#onUpdatePwmPeriod()`のようなコールバックや`KonashiObserver#onUpdate(KonashiEvent)`，`KonashiEvent.UPDATE_PWM_PERIOD`といったイベントを用意してあげてあとはユーザに任せるという解決策もアリだと思います

**Comment by izumin5210** [comment]
#42 にてPWM Duty/Period変更のコールバックを追加したので，本Issueはcloseします．
