### ISSUE TITLE
find の際に出てくるダイアログをボタン以外で閉じた場合 scan 処理が走り続ける

### ISSUE THREAD

**Issue by kiryuxxu** [YUKAI/konashi-android-sdk#9]
find の際に出てくるダイアログを戻るボタンやダイアログの外をタッチして閉じると scan 処理が走り続けたままになってしまいます。

https://github.com/e10dokup/konashi-v2-android-sdk/blob/54e4e6371139d10cb9798c0394f3d7c5f425364d/Konashi/konashi-v2-android-sdk/src/main/java/com/uxxu/konashi/lib/BleDeviceSelectionDialog.java#L89

`onDismissListener` にもキャンセル処理を登録したほうが良いと思います。

**Comment by izumin5210** [comment]
本Issueですが，該当コードはあらゆるデバイスに共通するものであるため後ほど別ライブラリとして切り出す予定です

**Comment by izumin5210** [comment]
#126 で対応
